check:
  - thoth-build
build:
  build-stratergy: Dockerfile
  dockerfile-path: Dockerfile
  registry: quay.io
  registry-org: thoth-station
  registry-project: package-extract
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "package-extract"
  overlay-contextpath: "package-extract/overlays/test/imagestreamtag.yaml"
